INSERT INTO tb_genre (name) VALUES('Ação');
INSERT INTO tb_genre (name) VALUES('Crime');
INSERT INTO tb_genre (name) VALUES('Aventura');
INSERT INTO tb_genre (name) VALUES('Drama');
INSERT INTO tb_genre (name) VALUES('Ficção Científica');

INSERT INTO tb_movie(title, sub_title, year,img_url,synopsis, genre_id) VALUES ('Mortal Kombat Legends', 'A Vingança de Scorpion',2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9xeEGUZjgiKlI69jwIOi0hjKUIk.jpg', 'Após o massacre cruel de sua família pelo mercenário Sub-Zero, Hanzo Hasashi é exilado no tortuoso Netherrealm, lá, em troca de sua servidão ao sinistro Quan Chi, ele tem a chance de vingar sua família - e ressuscita como Scorpion, uma alma perdida e vingativa. De volta ao Earthrealm, Lord Raiden reúne uma equipe de guerreiros de elite - o monge Shaolin Liu Kang, a oficial das Forças Especiais Sonya Blade e o ator de ação Johnny Cage - um grupo improvável de heróis com uma chance de salvar a humanidade. Para fazer isso, eles devem derrotar a horda de gladiadores do Outworld de Shang Tsung e vencer o torneio Mortal Kombat.',1);
INSERT INTO tb_movie(title, sub_title, year,img_url,synopsis, genre_id) VALUES ('Vanquish', '',2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mYM8x2Atv4MaLulaV0KVJWI1Djv.jpg', 'Uma mãe, Victoria, está tentando deixar seu passado sombrio como uma entregadora de drogas russa para trás, mas o policial aposentado Damon força Victoria a cumprir suas ordens, mantendo sua filha como refém.', 2);
INSERT INTO tb_movie(title, sub_title, year,img_url,synopsis, genre_id) VALUES ('Carga Explosiva 3', '',2008, 'https://www.themoviedb.org/t/p/w220_and_h330_face/hC4lRSuZA29l4NbmQ8sdvkpRkO5.jpg', 'Frank Martin é obrigado a conduzir Valentina, a filha de Leonid Vasilev, o chefe da Agência de Proteção Ambiental da Ucrânia. Ela foi sequestrada por Jonas Johnson, contratado por uma empresa de gerenciamento internacional de resíduos que deseja operar na Ucrânia. Para ter Frank e Valentina sob controle, Jonas prende em seus pulsos um dispositivo que determina que não possam se afastar muito do carro que os conduz, caso contrário o bracelete explode. Contando com a ajuda do inspetor Tarconi, Frank busca um meio de deixar a armadilha.', 3);
INSERT INTO tb_movie(title, sub_title, year,img_url,synopsis, genre_id) VALUES ('Venom', 'Tempo de Carnificina',2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/AhFRV5YxJamUZ4oZdxv6PI0ythi.jpg', 'O relacionamento entre Eddie e Venom (Tom Hardy) está evoluindo. Buscando a melhor forma de lidar com a inevitável simbiose, esse dois lados descobrem como viver juntos e, de alguma forma, se tornarem melhores juntos do que separados.', 1);
INSERT INTO tb_movie(title, sub_title, year,img_url,synopsis, genre_id) VALUES ('Sem Remorso', '',2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fPGeS6jgdLovQAKunNHX8l0avCy.jpg', 'Um agente da CIA busca vingança depois de sua namorada ter sido morta por um traficante de Baltimore.', 3);
INSERT INTO tb_movie(title, sub_title, year,img_url,synopsis, genre_id) VALUES ('Monstro', '',2021, 'https://www.themoviedb.org/t/p/w220_and_h330_face/9MJrBZlI1WqD1ftg0YT08jmmQ5e.jpg', 'Monstro conta a história de Steve Harmon (Kelvin Harrison Jr.), um aluno de 17 anos que é acusado de homicídio doloso. O filme mostra a dramática trajetória desse inteligente e simpático estudante do Harlem, que frequenta uma escola de elite, em uma batalha judicial complexa que pode deixá-lo para o resto da vida na prisão.', 4);
INSERT INTO tb_movie(title, sub_title, year,img_url,synopsis, genre_id) VALUES ('Star Wars', 'The Bad Batch',2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/sjxtIUCWR74yPPcZFfTsToepfWm.jpg', 'Os Mal Feitos precisam encontrar seu caminho numa galáxia em rápida transformação.', 5);
INSERT INTO tb_movie(title, sub_title, year,img_url,synopsis, genre_id) VALUES ('A Família Mitchell e a Revolta das Máquinas', '',2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/egxe0rPverBETHzV6COXFGL4edC.jpg', 'Katie Mitchell é aceita na faculdade de cinema dos seus sonhos e seu pai decide aproveitar para realizar uma viagem em família para levá-la à universidade. Porém, seus planos são interrompidos por uma revolução robótica e agora os Mitchells terão que unir forças em família para trabalhar juntos para salvar o mundo.',3);
INSERT INTO tb_movie(title, sub_title, year,img_url,synopsis, genre_id) VALUES ('French Exit', '',2021, 'https://www.themoviedb.org/t/p/w220_and_h330_face/xKTQAYkjKYJg9i3gpL2OUxsnotu.jpg', 'A socialite is decamping from Manhattan to Paris to live out her days after her dead husband’s fortune runs out. She cashes out whatever is left and goes with her son and her cat, who happens to be the embodiment of her long-dead partner.',4);
INSERT INTO tb_movie(title, sub_title, year,img_url,synopsis, genre_id) VALUES ('Deadpool', '',2016, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/en971MEXui9diirXlogOrPKmsEn.jpg', 'Baseado no anti-herói não convencional da Marvel Comics, Deadpool conta a história da origem do ex-agente das Forças Especiais que se tornou o mercenário Wade Wilson. Depois de ser submetido a um desonesto experimento que o deixa com poderes de cura acelerada, Wade adota o alter ego de Deadpool. Armado com suas novas habilidades e um senso de humor negro e distorcido, Deadpool persegue o homem que quase destruiu sua vida.', 3);
INSERT INTO tb_movie(title, sub_title, year,img_url,synopsis, genre_id) VALUES ('Guardiões da Galáxia', '',2014, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/i34ijHY5hr52uYcKZ48wq7K6yUs.jpg', 'O aventureiro do espaço Peter Quill torna-se presa de caçadores de recompensas depois que rouba a esfera de um vilão traiçoeiro, Ronan. Para escapar do perigo, ele faz uma aliança com um grupo de quatro extraterrestres. Quando Quill descobre que a esfera roubada possui um poder capaz de mudar os rumos do universo, ele e seu grupo deverão proteger o objeto para salvar o futuro da galáxia.', 1);

INSERT INTO tb_user(name, email, password) VALUES('Bob','bob@gmail.com', '$2y$12$x/p0FcLJlHjv9TRL2J/Ox.3RvaIL8PHHV1NP7f3Ijqb49Pso4X1Xy');
INSERT INTO tb_user(name, email, password) VALUES('Ana','ana@gmail', '$2y$12$x/p0FcLJlHjv9TRL2J/Ox.3RvaIL8PHHV1NP7f3Ijqb49Pso4X1Xy');

INSERT INTO tb_role (authority) VALUES('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES('ROLE_MEMBER');

INSERT INTO tb_user_roles(user_id, role_id) VALUES (1,1);
INSERT INTO tb_user_roles(user_id, role_id) VALUES (2,2);

INSERT INTO tb_review(text, user_id, movie_id)VALUES('Muito Bom!',1,1);
INSERT INTO tb_review(text, user_id, movie_id)VALUES('Adorei!',1,1);
INSERT INTO tb_review(text, user_id, movie_id)VALUES('Sensacional!',1,2);
INSERT INTO tb_review(text, user_id, movie_id)VALUES('Odiei!',2,1);
INSERT INTO tb_review(text, user_id, movie_id)VALUES('Até que é legal!',2,3);
